#!/usr/bin/env bash

MONITOR_COUNT=0
NEW_MONITOR_COUNT=0

while true; do
	NEW_MONITOR_COUNT=$(polybar -m | wc -l)
	if [ $NEW_MONITOR_COUNT != $MONITOR_COUNT ]; then
		MONITOR_COUNT=$NEW_MONITOR_COUNT
		/home/treborium/.screenlayout/duo-monitor.sh
		/home/treborium/.config/polybar/scripts/launch.sh
		echo "Change in number of monitors detected..."
	fi
	sleep 1.0
done